### PR TITLE
Rails Capestone Project

### PR DESCRIPTION
**Pull request by basem909**
## Project Requirements
- Build a mobile web application where you can manage your budget: you have a list of transactions associated with a category, so that you can see how much money you spent and on what.
- allows the user to:
   - register and log in, so that the data is private to them.
   - introduce new transactions associated with a category.
   - see the money spent on each category.
- Create these pages:
   - Splash screen.
   - Sign up and login pages.
   - Home page (catagories page).
   - Transactions page.
   - "Add a new category" page.
   - "Add a new transaction" page.
- Create unit and integration tests for all the most important components.

## Demo Link
- [Smart Finance](https://budget-app-rails-mod.herokuapp.com/)

## Documentation Video
- [Loom Video](https://www.loom.com/share/3fc3b421e4b8485d9ed30f5d2d2efe5d)

### CODE REVIEW

**Review by phelian23 — CHANGES_REQUESTED** [review]
Hi @basem909,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!


## Suggested changes
_Check the comments under the review._

- [ ] Good job deploying the app, however, when I try to interact with the app, I got this error
Capture 2
Kindly fix this. It is mostly caused when the database is not migrated to Heroku.

- [ ] One of your test examples is failing. Kindly fix it
Capture



You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by basem909** [comment]
## The first required change:
- I migrated the db and it is working fine now
- For the demo link But please use this user that I did the sign-up and authentication for it already:
   - email: basemshams1000@gmail.com
   - password: 123456
- This is just because I did an authentication token for the new signed-up user and since I do not have a production mailer server I had to authenticate it using the console which will not be available for u as a user.
- Or you can authenticate the account using this URL : "https://budget-app-rails-mod.herokuapp.com/confirmation?confirmation_token=< User.authentication_token >" but I am not sure how you would be able to get the token itself
- On the local device you will find the authentication link on rails server log so you can make sure about the sign-up functionallity.
## The second required change:
Screen Shot 2022-09-15 at 04 29 40
- As you can see on my local device there is no failure.

**Comment by prolajumokeoni** [comment]
Hi @basem909 Good job providing details to use to test the app 👍🏿 login works fine now 👏🏿

**Review by prolajumokeoni — APPROVED** [review]
Hi @basem909, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- No linter errors ✅ 
- Git flow was used correctly 🚀 
- Good design 💯 
- Good Pr title and description 💪🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
